import { computeDashboard, computeMeta } from '@/lib/admin/audit-log/dashboard';
import type { AdminAuditDashboardData, AuditLogMeta, AuditLogRow } from '@/lib/admin/audit-log/types';

const NOW = new Date('2024-05-18T09:15:00Z');

export const ADMIN_AUDIT_FALLBACK_ROWS: AuditLogRow[] = [
  {
    id: 'audit-fb-001',
    created_at: '2024-05-18T08:57:42Z',
    kind: 'LOGIN',
    category: 'security',
    action: 'LOGIN_SUCCESS',
    target_type: 'USER',
    target_id: 'usr-001',
    target: 'Joana Duarte',
    actor_id: 'usr-001',
    actor: 'Joana Duarte',
    note: 'Login via app web',
    details: { device: 'MacBook Pro', ip: '2001:8a0:1234:1::56' },
    payload: null,
    meta: { session_id: 'sess-9a1' },
    ip: '2001:8a0:1234:1::56',
    user_agent: 'Chrome/124.0 macOS',
  },
  {
    id: 'audit-fb-002',
    created_at: '2024-05-18T08:31:04Z',
    kind: 'TRAINING_PLAN_UPDATE',
    category: 'plans',
    action: 'PLAN_WEEK_ADJUSTED',
    target_type: 'TRAINING_PLAN',
    target_id: 'plan-442',
    target: 'Plano Hipertrofia · João Borges',
    actor_id: 'pt-004',
    actor: 'Miguel Carvalho',
    note: 'Reorganizou microciclo para período pré-competição',
    details: { duration_weeks: 10 },
    payload: null,
    meta: { field: 'duration_weeks', old: 12, new: 10 },
    ip: '85.246.21.16',
    user_agent: 'Chrome/124.0 Windows',
  },
  {
    id: 'audit-fb-003',
    created_at: '2024-05-18T08:05:22Z',
    kind: 'USER_UPDATE',
    category: 'users',
    action: 'PROFILE_APPROVED',
    target_type: 'USER',
    target_id: 'usr-317',
    target: 'Sara Pires',
    actor_id: 'adm-001',
    actor: 'Ana Rodrigues',
    note: 'Aprovou documentação de fatura',
    details: { previous_status: 'pending', next_status: 'active' },
    payload: null,
    meta: null,
    ip: '2a02:410:ac4:1200::15',
    user_agent: 'Edge/123.0 Windows',
  },
  {
    id: 'audit-fb-004',
    created_at: '2024-05-18T07:12:18Z',
    kind: 'RESET_PASSWORD',
    category: 'security',
    action: 'PASSWORD_RESET_REQUESTED',
    target_type: 'USER',
    target_id: 'usr-229',
    target: 'Ricardo Fonseca',
    actor_id: 'usr-229',
    actor: 'Ricardo Fonseca',
    note: 'Recuperação via email',
    details: null,
    payload: null,
    meta: { channel: 'email' },
    ip: '193.123.12.23',
    user_agent: 'iOS/17.4 Safari',
  },
  {
    id: 'audit-fb-005',
    created_at: '2024-05-18T06:45:10Z',
    kind: 'TRAINING_PLAN_CREATE',
    category: 'plans',
    action: 'PLAN_CREATED',
    target_type: 'TRAINING_PLAN',
    target_id: 'plan-458',
    target: 'Reabilitação LCA · Pedro Vaz',
    actor_id: 'pt-012',
    actor: 'Carolina Matos',
    note: 'Plano base criado a partir de template de reabilitação',
    details: { template: 'knee-return' },
    payload: null,
    meta: null,
    ip: '95.92.12.98',
    user_agent: 'Chrome/124.0 macOS',
  },
  {
    id: 'audit-fb-006',
    created_at: '2024-05-18T06:12:03Z',
    kind: 'SESSION',
    category: 'sessions',
    action: 'SESSION_CHECK_IN',
    target_type: 'SESSION',
    target_id: 'sess-912',
    target: 'Avaliação funcional · Centro Lisboa',
    actor_id: 'pt-004',
    actor: 'Miguel Carvalho',
    note: 'Confirmou presença do cliente',
    details: { client: 'João Borges' },
    payload: null,
    meta: null,
    ip: '85.246.21.16',
    user_agent: 'Chrome/124.0 Windows',
  },
  {
    id: 'audit-fb-007',
    created_at: '2024-05-18T05:54:46Z',
    kind: 'USER_SUSPEND',
    category: 'users',
    action: 'ACCOUNT_SUSPENDED',
    target_type: 'USER',
    target_id: 'usr-204',
    target: 'Cláudia Gouveia',
    actor_id: 'adm-001',
    actor: 'Ana Rodrigues',
    note: 'Suspensão preventiva por faturação falhada',
    details: { invoices_overdue: 3 },
    payload: null,
    meta: null,
    ip: '2a02:410:ac4:1200::15',
    user_agent: 'Edge/123.0 Windows',
  },
  {
    id: 'audit-fb-008',
    created_at: '2024-05-17T20:42:32Z',
    kind: 'TRAINING_PLAN_DELETE',
    category: 'plans',
    action: 'PLAN_ARCHIVED',
    target_type: 'TRAINING_PLAN',
    target_id: 'plan-399',
    target: 'Crossfit Intermédio · Marta Gomes',
    actor_id: 'pt-006',
    actor: 'Tiago Loureiro',
    note: 'Plano substituído por versão revista',
    details: null,
    payload: null,
    meta: null,
    ip: '188.80.54.12',
    user_agent: 'Firefox/126.0 Windows',
  },
  {
    id: 'audit-fb-009',
    created_at: '2024-05-17T19:27:05Z',
    kind: 'LOGIN',
    category: 'security',
    action: 'LOGIN_SUCCESS',
    target_type: 'USER',
    target_id: 'adm-001',
    target: 'Ana Rodrigues',
    actor_id: 'adm-001',
    actor: 'Ana Rodrigues',
    note: 'Sessão administrativa iniciada',
    details: null,
    payload: null,
    meta: { session_id: 'sess-98f' },
    ip: '2a02:410:ac4:1200::15',
    user_agent: 'Edge/123.0 Windows',
  },
  {
    id: 'audit-fb-010',
    created_at: '2024-05-17T18:11:49Z',
    kind: 'TRAINING_PLAN_PUBLISH',
    category: 'plans',
    action: 'PLAN_PUBLISHED',
    target_type: 'TRAINING_PLAN',
    target_id: 'plan-441',
    target: 'PT · Recompõe 8 semanas',
    actor_id: 'pt-014',
    actor: 'Vera Campos',
    note: 'Plano passou a visível para o cliente',
    details: { publish_channel: 'app' },
    payload: null,
    meta: null,
    ip: '176.61.44.90',
    user_agent: 'Chrome/124.0 Android',
  },
  {
    id: 'audit-fb-011',
    created_at: '2024-05-17T17:33:12Z',
    kind: 'NOTIFICATION',
    category: 'notifications',
    action: 'PUSH_DISPATCHED',
    target_type: 'NOTIFICATION',
    target_id: 'push-772',
    target: 'Push semanal · Dicas de recuperação',
    actor_id: 'adm-002',
    actor: 'Pedro Oliveira',
    note: 'Push enviado para 1.842 clientes',
    details: { audience: 1842 },
    payload: null,
    meta: null,
    ip: '193.136.12.11',
    user_agent: 'Safari/17.4 macOS',
  },
  {
    id: 'audit-fb-012',
    created_at: '2024-05-17T16:48:03Z',
    kind: 'USER_CREATE',
    category: 'users',
    action: 'TRAINER_INVITED',
    target_type: 'USER',
    target_id: 'pt-019',
    target: 'Daniel Faria',
    actor_id: 'adm-002',
    actor: 'Pedro Oliveira',
    note: 'Convite enviado para reforçar equipa norte',
    details: { role: 'PERSONAL_TRAINER' },
    payload: null,
    meta: null,
    ip: '193.136.12.11',
    user_agent: 'Safari/17.4 macOS',
  },
  {
    id: 'audit-fb-013',
    created_at: '2024-05-17T15:22:47Z',
    kind: 'TRAINING_PLAN_CLONE',
    category: 'plans',
    action: 'PLAN_CLONED',
    target_type: 'TRAINING_PLAN',
    target_id: 'plan-430',
    target: 'Força Base · Mariana Cruz',
    actor_id: 'pt-012',
    actor: 'Carolina Matos',
    note: 'Clonou plano para nova cliente com objetivos similares',
    details: { clone_from: 'plan-415' },
    payload: null,
    meta: null,
    ip: '95.92.12.98',
    user_agent: 'Chrome/124.0 macOS',
  },
  {
    id: 'audit-fb-014',
    created_at: '2024-05-17T14:51:02Z',
    kind: 'LOGIN',
    category: 'security',
    action: 'LOGIN_FAILED',
    target_type: 'USER',
    target_id: 'usr-204',
    target: 'Cláudia Gouveia',
    actor_id: 'usr-204',
    actor: 'Cláudia Gouveia',
    note: 'Senha inválida — tentativa bloqueada',
    details: { attempts: 3 },
    payload: null,
    meta: null,
    ip: '109.52.33.201',
    user_agent: 'Android/14 Chrome',
  },
  {
    id: 'audit-fb-015',
    created_at: '2024-05-17T13:38:18Z',
    kind: 'USER_APPROVE',
    category: 'users',
    action: 'TRAINER_APPROVED',
    target_type: 'USER',
    target_id: 'pt-017',
    target: 'Helena Sousa',
    actor_id: 'adm-001',
    actor: 'Ana Rodrigues',
    note: 'Certificação verificada e contrato assinado',
    details: { certificate: 'EXOS-2023' },
    payload: null,
    meta: null,
    ip: '2a02:410:ac4:1200::15',
    user_agent: 'Edge/123.0 Windows',
  },
  {
    id: 'audit-fb-016',
    created_at: '2024-05-17T11:26:09Z',
    kind: 'TRAINING_PLAN_UPDATE',
    category: 'plans',
    action: 'PLAN_MACRO_UPDATED',
    target_type: 'TRAINING_PLAN',
    target_id: 'plan-401',
    target: 'Endurance Base · Luís Lima',
    actor_id: 'pt-003',
    actor: 'Teresa Silva',
    note: 'Ajustou volume de corrida para 34km semanais',
    details: { weekly_run_km: 34 },
    payload: null,
    meta: null,
    ip: '83.132.14.44',
    user_agent: 'Safari/17.4 iPadOS',
  },
  {
    id: 'audit-fb-017',
    created_at: '2024-05-17T09:45:51Z',
    kind: 'LOGOUT',
    category: 'security',
    action: 'LOGOUT',
    target_type: 'USER',
    target_id: 'adm-002',
    target: 'Pedro Oliveira',
    actor_id: 'adm-002',
    actor: 'Pedro Oliveira',
    note: 'Sessão expirada após 3h de inatividade',
    details: null,
    payload: null,
    meta: null,
    ip: '193.136.12.11',
    user_agent: 'Safari/17.4 macOS',
  },
  {
    id: 'audit-fb-018',
    created_at: '2024-05-17T08:12:14Z',
    kind: 'NOTIFICATION',
    category: 'notifications',
    action: 'EMAIL_BULK_SENT',
    target_type: 'NOTIFICATION',
    target_id: 'email-552',
    target: 'Resumo semanal clientes — Norte',
    actor_id: 'adm-002',
    actor: 'Pedro Oliveira',
    note: 'Email automático com taxa de entrega 98%',
    details: { delivered: 1250, bounced: 24 },
    payload: null,
    meta: null,
    ip: '193.136.12.11',
    user_agent: 'Safari/17.4 macOS',
  },
  {
    id: 'audit-fb-019',
    created_at: '2024-05-17T07:01:33Z',
    kind: 'USER_DELETE',
    category: 'users',
    action: 'ACCOUNT_DELETED',
    target_type: 'USER',
    target_id: 'usr-188',
    target: 'Nuno Reis',
    actor_id: 'adm-003',
    actor: 'João Santos',
    note: 'Remoção solicitada pelo cliente (RGPD)',
    details: { export_delivered_at: '2024-05-16T18:44:00Z' },
    payload: null,
    meta: null,
    ip: '145.239.132.4',
    user_agent: 'Firefox/126.0 Linux',
  },
  {
    id: 'audit-fb-020',
    created_at: '2024-05-16T18:22:05Z',
    kind: 'LOGIN',
    category: 'security',
    action: 'LOGIN_SUCCESS',
    target_type: 'USER',
    target_id: 'pt-012',
    target: 'Carolina Matos',
    actor_id: 'pt-012',
    actor: 'Carolina Matos',
    note: 'Login a partir de dispositivo móvel novo',
    details: { device: 'iPhone 15', location: 'Porto' },
    payload: null,
    meta: null,
    ip: '95.92.12.98',
    user_agent: 'Safari/17.4 iOS',
  },
];

export const ADMIN_AUDIT_META_FALLBACK: AuditLogMeta = computeMeta(ADMIN_AUDIT_FALLBACK_ROWS);

export const ADMIN_AUDIT_DASHBOARD_FALLBACK: AdminAuditDashboardData = computeDashboard(
  ADMIN_AUDIT_FALLBACK_ROWS,
  NOW,
);
