import { buildAdminExercisesDashboard } from '../admin/exercises/dashboard';
import { type AdminExerciseRecord } from '../admin/exercises/types';

const BASE_EXERCISES: AdminExerciseRecord[] = [
  {
    id: 'fb-ex-001',
    name: 'Back Squat',
    description: 'Agachamento com barra focado em força máxima e estabilidade do core.',
    muscleGroup: 'Quadríceps, Glúteos',
    equipment: 'Barra olímpica, Rack',
    difficulty: 'Difícil',
    videoUrl: 'https://videos.fitbox.pt/back-squat.mp4',
    isGlobal: true,
    isPublished: true,
    publishedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    ownerId: null,
    ownerName: null,
    ownerEmail: null,
    creatorId: 'admin-001',
    creatorName: 'Ana Marques',
    creatorEmail: 'ana@fitnesspro.pt',
  },
  {
    id: 'fb-ex-002',
    name: 'Press de Ombros com Halteres',
    description: 'Séries controladas com foco em estabilidade escapular e força bilateral.',
    muscleGroup: 'Ombros',
    equipment: 'Halteres, Banco',
    difficulty: 'Média',
    videoUrl: 'https://videos.fitbox.pt/dumbbell-press.mp4',
    isGlobal: true,
    isPublished: true,
    publishedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    ownerId: null,
    ownerName: null,
    ownerEmail: null,
    creatorId: 'admin-001',
    creatorName: 'Ana Marques',
    creatorEmail: 'ana@fitnesspro.pt',
  },
  {
    id: 'fb-ex-003',
    name: 'Remada Curvada',
    description: 'Execução em supinação para aumentar activação dos flexores e estabilidade lombar.',
    muscleGroup: 'Costas, Bíceps',
    equipment: 'Barra olímpica',
    difficulty: 'Média',
    videoUrl: 'https://videos.fitbox.pt/bent-over-row.mp4',
    isGlobal: true,
    isPublished: true,
    publishedAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 44 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
    ownerId: null,
    ownerName: null,
    ownerEmail: null,
    creatorId: 'admin-002',
    creatorName: 'João Pires',
    creatorEmail: 'joao@fitnesspro.pt',
  },
  {
    id: 'fb-ex-004',
    name: 'Deadlift Romeno',
    description: 'Foco em cadeia posterior com amplitude controlada e tempo excêntrico aumentado.',
    muscleGroup: 'Isquiotibiais, Glúteos',
    equipment: 'Barra olímpica, Discos',
    difficulty: 'Difícil',
    videoUrl: 'https://videos.fitbox.pt/romanian-deadlift.mp4',
    isGlobal: true,
    isPublished: true,
    publishedAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 61 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    ownerId: null,
    ownerName: null,
    ownerEmail: null,
    creatorId: 'admin-003',
    creatorName: 'Maria Costa',
    creatorEmail: 'maria@fitnesspro.pt',
  },
  {
    id: 'fb-ex-005',
    name: 'Prancha com Alcance',
    description: 'Variação anti-rotação para estabilidade do core e controlo respiratório.',
    muscleGroup: 'Core',
    equipment: 'Colchonete',
    difficulty: 'Média',
    videoUrl: 'https://videos.fitbox.pt/plank-reach.mp4',
    isGlobal: true,
    isPublished: true,
    publishedAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    ownerId: null,
    ownerName: null,
    ownerEmail: null,
    creatorId: 'admin-003',
    creatorName: 'Maria Costa',
    creatorEmail: 'maria@fitnesspro.pt',
  },
  {
    id: 'fb-ex-006',
    name: 'Lunge Reverso com Press',
    description: 'Coordenação unilateral com foco em estabilidade de joelho e ombro.',
    muscleGroup: 'Glúteos, Ombros',
    equipment: 'Halteres',
    difficulty: 'Média',
    videoUrl: 'https://videos.fitbox.pt/reverse-lunge-press.mp4',
    isGlobal: true,
    isPublished: true,
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    ownerId: null,
    ownerName: null,
    ownerEmail: null,
    creatorId: 'admin-004',
    creatorName: 'Pedro Almeida',
    creatorEmail: 'pedro@fitnesspro.pt',
  },
  {
    id: 'fb-ex-007',
    name: 'Passada no TRX',
    description: 'Estímulo unilateral com suporte parcial do peso corporal e foco em controlo excêntrico.',
    muscleGroup: 'Quadríceps, Core',
    equipment: 'TRX',
    difficulty: 'Média',
    videoUrl: 'https://videos.fitbox.pt/trx-lunge.mp4',
    isGlobal: false,
    isPublished: false,
    publishedAt: null,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    ownerId: 'trainer-001',
    ownerName: 'Rita Figueiredo',
    ownerEmail: 'rita@fitnesspro.pt',
    creatorId: 'trainer-001',
    creatorName: 'Rita Figueiredo',
    creatorEmail: 'rita@fitnesspro.pt',
  },
  {
    id: 'fb-ex-008',
    name: 'Kettlebell Swing',
    description: 'Potência da cadeia posterior com foco em extensão de anca explosiva.',
    muscleGroup: 'Glúteos, Isquiotibiais',
    equipment: 'Kettlebell',
    difficulty: 'Média',
    videoUrl: 'https://videos.fitbox.pt/kb-swing.mp4',
    isGlobal: true,
    isPublished: true,
    publishedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    ownerId: null,
    ownerName: null,
    ownerEmail: null,
    creatorId: 'admin-004',
    creatorName: 'Pedro Almeida',
    creatorEmail: 'pedro@fitnesspro.pt',
  },
  {
    id: 'fb-ex-009',
    name: 'Puxada na Barra Fixa com Banda',
    description: 'Progressão assistida para reforço de grande dorsal e flexores do cotovelo.',
    muscleGroup: 'Costas, Bíceps',
    equipment: 'Barra fixa, Banda elástica',
    difficulty: 'Média',
    videoUrl: 'https://videos.fitbox.pt/pullup-band.mp4',
    isGlobal: true,
    isPublished: true,
    publishedAt: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 52 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
    ownerId: null,
    ownerName: null,
    ownerEmail: null,
    creatorId: 'admin-002',
    creatorName: 'João Pires',
    creatorEmail: 'joao@fitnesspro.pt',
  },
  {
    id: 'fb-ex-010',
    name: 'Leg Press Unilateral',
    description: 'Trabalho unilateral controlado para corrigir assimetrias de força.',
    muscleGroup: 'Quadríceps',
    equipment: 'Leg Press',
    difficulty: 'Média',
    videoUrl: 'https://videos.fitbox.pt/single-leg-press.mp4',
    isGlobal: false,
    isPublished: false,
    publishedAt: null,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    ownerId: 'trainer-002',
    ownerName: 'Tiago Neves',
    ownerEmail: 'tiago@fitnesspro.pt',
    creatorId: 'trainer-002',
    creatorName: 'Tiago Neves',
    creatorEmail: 'tiago@fitnesspro.pt',
  },
  {
    id: 'fb-ex-011',
    name: 'Pliometria em Caixa',
    description: 'Saltar e aterrar com foco em absorção de impacto e estabilidade do joelho.',
    muscleGroup: 'Quadríceps, Glúteos',
    equipment: 'Caixa pliométrica',
    difficulty: 'Difícil',
    videoUrl: 'https://videos.fitbox.pt/box-jump.mp4',
    isGlobal: true,
    isPublished: true,
    publishedAt: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 70 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    ownerId: null,
    ownerName: null,
    ownerEmail: null,
    creatorId: 'admin-005',
    creatorName: 'Sara Nogueira',
    creatorEmail: 'sara@fitnesspro.pt',
  },
  {
    id: 'fb-ex-012',
    name: 'Elevação Lateral em Cavo',
    description: 'Isolamento deltoidal com tensão contínua e cadência controlada.',
    muscleGroup: 'Ombros',
    equipment: 'Cabo',
    difficulty: 'Média',
    videoUrl: 'https://videos.fitbox.pt/cable-lateral-raise.mp4',
    isGlobal: true,
    isPublished: true,
    publishedAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    ownerId: null,
    ownerName: null,
    ownerEmail: null,
    creatorId: 'admin-005',
    creatorName: 'Sara Nogueira',
    creatorEmail: 'sara@fitnesspro.pt',
  },
];

type Options = {
  rangeDays?: number;
  page?: number;
  pageSize?: number;
};

export function fallbackAdminExercisesDashboard(options: Options = {}) {
  const rangeDays = options.rangeDays ?? 180;
  const pageSize = options.pageSize ?? 20;
  const page = Math.max(0, options.page ?? 0);

  const start = page * pageSize;
  const tableRecords = BASE_EXERCISES.slice(start, start + pageSize);

  return buildAdminExercisesDashboard({
    allRecords: BASE_EXERCISES,
    rangeDays,
    tableRecords,
    tableTotal: BASE_EXERCISES.length,
    page,
    pageSize,
  });
}
