import { buildAdminClientsDashboard } from '@/lib/admin/clients/dashboard';
import type { AdminClientRecord, AdminClientsDashboardData } from '@/lib/admin/clients/types';

const NOW = new Date();

function daysAgo(days: number) {
  const date = new Date(NOW.getTime() - days * 24 * 60 * 60 * 1000);
  return date.toISOString();
}

function daysAhead(days: number) {
  const date = new Date(NOW.getTime() + days * 24 * 60 * 60 * 1000);
  return date.toISOString();
}

const SAMPLE_CLIENTS: AdminClientRecord[] = [
  {
    id: 'cli-1001',
    name: 'Ana Marques',
    email: 'ana.marques@example.com',
    status: 'ACTIVE',
    approved: true,
    active: true,
    createdAt: daysAgo(220),
    lastActiveAt: daysAgo(2),
    lastSignInAt: daysAgo(1),
    trainerId: 'pt-2001',
    trainerName: 'Miguel Tavares',
    goals: ['força', 'mobilidade'],
    tags: ['premium', 'corporate'],
    sessionsCompleted30d: 6,
    sessionsCompletedRange: 20,
    sessionsScheduled7d: 2,
    sessionsCancelled30d: 0,
    lastSessionAt: daysAgo(3),
    nextSessionAt: daysAhead(2),
    walletBalance: 85,
    walletCurrency: 'EUR',
    walletUpdatedAt: daysAgo(1),
    invoicesPaidTotal: 1280,
    invoicesPaidTotal30d: 320,
    invoicesPendingTotal: 0,
    invoicesPendingTotal30d: 0,
    invoicesPaidCount: 14,
    invoicesPendingCount: 0,
    planCount: 4,
    activePlanCount: 1,
    lastPlanTitle: 'Plano Força 12 semanas',
    lastPlanUpdatedAt: daysAgo(5),
    satisfactionScore: 0.92,
    churnRiskScore: 0.12,
    engagementScore: 0.86,
  },
  {
    id: 'cli-1002',
    name: 'João Pires',
    email: 'joao.pires@example.com',
    status: 'ACTIVE',
    approved: true,
    active: true,
    createdAt: daysAgo(410),
    lastActiveAt: daysAgo(6),
    lastSignInAt: daysAgo(4),
    trainerId: 'pt-2002',
    trainerName: 'Sara Nogueira',
    goals: ['perda de peso'],
    tags: ['nutrição', 'focus-cardio'],
    sessionsCompleted30d: 4,
    sessionsCompletedRange: 16,
    sessionsScheduled7d: 1,
    sessionsCancelled30d: 1,
    lastSessionAt: daysAgo(4),
    nextSessionAt: daysAhead(3),
    walletBalance: 12,
    walletCurrency: 'EUR',
    walletUpdatedAt: daysAgo(3),
    invoicesPaidTotal: 860,
    invoicesPaidTotal30d: 180,
    invoicesPendingTotal: 60,
    invoicesPendingTotal30d: 60,
    invoicesPaidCount: 9,
    invoicesPendingCount: 1,
    planCount: 3,
    activePlanCount: 1,
    lastPlanTitle: 'Plano HIIT + Nutrição',
    lastPlanUpdatedAt: daysAgo(7),
    satisfactionScore: 0.74,
    churnRiskScore: 0.38,
    engagementScore: 0.62,
  },
  {
    id: 'cli-1003',
    name: 'Maria Costa',
    email: 'maria.costa@example.com',
    status: 'PENDING',
    approved: false,
    active: true,
    createdAt: daysAgo(8),
    lastActiveAt: daysAgo(5),
    lastSignInAt: daysAgo(6),
    trainerId: 'pt-2003',
    trainerName: 'Ricardo Fonseca',
    goals: ['reabilitação'],
    tags: ['fisioterapia'],
    sessionsCompleted30d: 1,
    sessionsCompletedRange: 1,
    sessionsScheduled7d: 0,
    sessionsCancelled30d: 0,
    lastSessionAt: daysAgo(7),
    nextSessionAt: null,
    walletBalance: 0,
    walletCurrency: 'EUR',
    walletUpdatedAt: daysAgo(8),
    invoicesPaidTotal: 90,
    invoicesPaidTotal30d: 90,
    invoicesPendingTotal: 0,
    invoicesPendingTotal30d: 0,
    invoicesPaidCount: 1,
    invoicesPendingCount: 0,
    planCount: 1,
    activePlanCount: 0,
    lastPlanTitle: 'Avaliação inicial',
    lastPlanUpdatedAt: daysAgo(8),
    satisfactionScore: 0.55,
    churnRiskScore: 0.58,
    engagementScore: 0.32,
  },
  {
    id: 'cli-1004',
    name: 'Pedro Almeida',
    email: 'pedro.almeida@example.com',
    status: 'ACTIVE',
    approved: true,
    active: true,
    createdAt: daysAgo(95),
    lastActiveAt: daysAgo(1),
    lastSignInAt: daysAgo(1),
    trainerId: 'pt-2001',
    trainerName: 'Miguel Tavares',
    goals: ['ganho massa'],
    tags: ['powerlifting'],
    sessionsCompleted30d: 8,
    sessionsCompletedRange: 18,
    sessionsScheduled7d: 2,
    sessionsCancelled30d: 0,
    lastSessionAt: daysAgo(1),
    nextSessionAt: daysAhead(1),
    walletBalance: 140,
    walletCurrency: 'EUR',
    walletUpdatedAt: daysAgo(0),
    invoicesPaidTotal: 1320,
    invoicesPaidTotal30d: 420,
    invoicesPendingTotal: 0,
    invoicesPendingTotal30d: 0,
    invoicesPaidCount: 10,
    invoicesPendingCount: 0,
    planCount: 2,
    activePlanCount: 1,
    lastPlanTitle: 'Plano Strength X',
    lastPlanUpdatedAt: daysAgo(3),
    satisfactionScore: 0.88,
    churnRiskScore: 0.18,
    engagementScore: 0.91,
  },
  {
    id: 'cli-1005',
    name: 'Rita Figueiredo',
    email: 'rita.figueiredo@example.com',
    status: 'SUSPENDED',
    approved: true,
    active: false,
    createdAt: daysAgo(530),
    lastActiveAt: daysAgo(80),
    lastSignInAt: daysAgo(84),
    trainerId: null,
    trainerName: null,
    goals: ['bem-estar'],
    tags: ['pausado'],
    sessionsCompleted30d: 0,
    sessionsCompletedRange: 0,
    sessionsScheduled7d: 0,
    sessionsCancelled30d: 0,
    lastSessionAt: daysAgo(90),
    nextSessionAt: null,
    walletBalance: -18,
    walletCurrency: 'EUR',
    walletUpdatedAt: daysAgo(70),
    invoicesPaidTotal: 460,
    invoicesPaidTotal30d: 0,
    invoicesPendingTotal: 45,
    invoicesPendingTotal30d: 45,
    invoicesPaidCount: 6,
    invoicesPendingCount: 1,
    planCount: 4,
    activePlanCount: 0,
    lastPlanTitle: 'Plano Manutenção',
    lastPlanUpdatedAt: daysAgo(120),
    satisfactionScore: 0.42,
    churnRiskScore: 0.82,
    engagementScore: 0.12,
  },
  {
    id: 'cli-1006',
    name: 'Diogo Rocha',
    email: 'diogo.rocha@example.com',
    status: 'ACTIVE',
    approved: true,
    active: true,
    createdAt: daysAgo(150),
    lastActiveAt: daysAgo(10),
    lastSignInAt: daysAgo(12),
    trainerId: 'pt-2004',
    trainerName: 'Helena Duarte',
    goals: ['performance'],
    tags: ['at-risk'],
    sessionsCompleted30d: 2,
    sessionsCompletedRange: 8,
    sessionsScheduled7d: 1,
    sessionsCancelled30d: 2,
    lastSessionAt: daysAgo(11),
    nextSessionAt: daysAhead(4),
    walletBalance: -32,
    walletCurrency: 'EUR',
    walletUpdatedAt: daysAgo(8),
    invoicesPaidTotal: 610,
    invoicesPaidTotal30d: 120,
    invoicesPendingTotal: 80,
    invoicesPendingTotal30d: 60,
    invoicesPaidCount: 7,
    invoicesPendingCount: 2,
    planCount: 3,
    activePlanCount: 1,
    lastPlanTitle: 'Plano Performance Sprint',
    lastPlanUpdatedAt: daysAgo(6),
    satisfactionScore: 0.58,
    churnRiskScore: 0.66,
    engagementScore: 0.44,
  },
  {
    id: 'cli-1007',
    name: 'Sara Nogueira',
    email: 'sara.nogueira@example.com',
    status: 'ACTIVE',
    approved: true,
    active: true,
    createdAt: daysAgo(32),
    lastActiveAt: daysAgo(0),
    lastSignInAt: daysAgo(0),
    trainerId: 'pt-2005',
    trainerName: 'Ana Pereira',
    goals: ['corrida'],
    tags: ['novo'],
    sessionsCompleted30d: 3,
    sessionsCompletedRange: 3,
    sessionsScheduled7d: 1,
    sessionsCancelled30d: 0,
    lastSessionAt: daysAgo(0),
    nextSessionAt: daysAhead(5),
    walletBalance: 32,
    walletCurrency: 'EUR',
    walletUpdatedAt: daysAgo(0),
    invoicesPaidTotal: 240,
    invoicesPaidTotal30d: 240,
    invoicesPendingTotal: 0,
    invoicesPendingTotal30d: 0,
    invoicesPaidCount: 3,
    invoicesPendingCount: 0,
    planCount: 1,
    activePlanCount: 1,
    lastPlanTitle: 'Plano Corrida 5K',
    lastPlanUpdatedAt: daysAgo(2),
    satisfactionScore: 0.81,
    churnRiskScore: 0.24,
    engagementScore: 0.68,
  },
  {
    id: 'cli-1008',
    name: 'Luís Carvalho',
    email: 'luis.carvalho@example.com',
    status: 'ACTIVE',
    approved: true,
    active: true,
    createdAt: daysAgo(280),
    lastActiveAt: daysAgo(3),
    lastSignInAt: daysAgo(3),
    trainerId: 'pt-2002',
    trainerName: 'Sara Nogueira',
    goals: ['condicionamento'],
    tags: ['corporate'],
    sessionsCompleted30d: 5,
    sessionsCompletedRange: 15,
    sessionsScheduled7d: 1,
    sessionsCancelled30d: 1,
    lastSessionAt: daysAgo(2),
    nextSessionAt: daysAhead(6),
    walletBalance: 55,
    walletCurrency: 'EUR',
    walletUpdatedAt: daysAgo(1),
    invoicesPaidTotal: 720,
    invoicesPaidTotal30d: 210,
    invoicesPendingTotal: 0,
    invoicesPendingTotal30d: 0,
    invoicesPaidCount: 8,
    invoicesPendingCount: 0,
    planCount: 2,
    activePlanCount: 1,
    lastPlanTitle: 'Plano Metcon',
    lastPlanUpdatedAt: daysAgo(4),
    satisfactionScore: 0.75,
    churnRiskScore: 0.34,
    engagementScore: 0.7,
  },
];

export function getAdminClientsDashboardFallback(): AdminClientsDashboardData {
  return buildAdminClientsDashboard(SAMPLE_CLIENTS, {
    fallback: true,
    weeks: 12,
    now: NOW,
  });
}
