import { buildTrainerWorkoutsDashboard } from '@/lib/trainer/workouts/dashboard';
import type { TrainerWorkoutRecord, TrainerWorkoutsDashboardData } from '@/lib/trainer/workouts/types';

function addMinutes(base: Date, minutes: number) {
  const date = new Date(base);
  date.setMinutes(date.getMinutes() + minutes);
  return date;
}

function addDays(base: Date, days: number) {
  const date = new Date(base);
  date.setDate(date.getDate() + days);
  return date;
}

function iso(date: Date) {
  return date.toISOString();
}

type TrainerWorkoutSeed = TrainerWorkoutRecord & { trainerSeed: string };

const now = new Date();
const base = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 7, 30, 0, 0);

const FALLBACK_TRAINER_WORKOUTS: TrainerWorkoutSeed[] = [
  {
    trainerSeed: 'trainer-joao',
    id: 'tw-001',
    title: 'Força total corpo inteiro',
    trainerId: 'trainer-joao',
    clientId: 'client-ana',
    clientName: 'Ana Marques',
    clientEmail: 'ana.marques@fitnesspro.pt',
    startAt: iso(addMinutes(base, 90)),
    endAt: iso(addMinutes(base, 150)),
    durationMinutes: 60,
    status: 'SCHEDULED',
    attendanceStatus: 'CONFIRMED',
    location: 'Box principal',
    planId: 'tp-001',
    planTitle: 'Base de força 8 semanas',
    focusArea: 'Força',
    intensity: 'Alta',
    notes: 'Incluir progressão no agachamento.',
  },
  {
    trainerSeed: 'trainer-joao',
    id: 'tw-002',
    title: 'HIIT + Core',
    trainerId: 'trainer-joao',
    clientId: 'client-pedro',
    clientName: 'Pedro Almeida',
    clientEmail: 'pedro.almeida@fitnesspro.pt',
    startAt: iso(addMinutes(base, 210)),
    endAt: iso(addMinutes(base, 270)),
    durationMinutes: 60,
    status: 'SCHEDULED',
    attendanceStatus: 'PENDING',
    location: 'Estúdio 2',
    planId: 'tp-002',
    planTitle: 'Hipertrofia membros inferiores',
    focusArea: 'Resistência',
    intensity: 'Média',
    notes: 'Rever técnica de levantamento terra.',
  },
  {
    trainerSeed: 'trainer-joao',
    id: 'tw-003',
    title: 'Mobilidade e estabilidade',
    trainerId: 'trainer-joao',
    clientId: 'client-rita',
    clientName: 'Rita Figueiredo',
    clientEmail: 'rita.figueiredo@fitnesspro.pt',
    startAt: iso(addDays(addMinutes(base, 60), 1)),
    endAt: iso(addDays(addMinutes(base, 120), 1)),
    durationMinutes: 60,
    status: 'SCHEDULED',
    attendanceStatus: 'UPCOMING',
    location: 'Sala de mobilidade',
    planId: 'tp-003',
    planTitle: 'Recuperação pós-lesão',
    focusArea: 'Mobilidade',
    intensity: 'Baixa',
    notes: 'Dar feedback ao fisioterapeuta.',
  },
  {
    trainerSeed: 'trainer-joao',
    id: 'tw-004',
    title: 'Treino força membro inferior',
    trainerId: 'trainer-joao',
    clientId: 'client-ines',
    clientName: 'Inês Carvalho',
    clientEmail: 'ines.carvalho@fitnesspro.pt',
    startAt: iso(addDays(addMinutes(base, 180), -1)),
    endAt: iso(addDays(addMinutes(base, 240), -1)),
    durationMinutes: 60,
    status: 'COMPLETED',
    attendanceStatus: 'COMPLETED',
    location: 'Box principal',
    planId: 'tp-005',
    planTitle: 'Preparação trail 50K',
    focusArea: 'Força',
    intensity: 'Alta',
    notes: 'Excelente execução, aumentar volume na próxima sessão.',
  },
  {
    trainerSeed: 'trainer-joao',
    id: 'tw-005',
    title: 'Treino de recuperação ativa',
    trainerId: 'trainer-joao',
    clientId: 'client-nuno',
    clientName: 'Nuno Ribeiro',
    clientEmail: 'nuno.ribeiro@fitnesspro.pt',
    startAt: iso(addDays(addMinutes(base, 300), -3)),
    endAt: iso(addDays(addMinutes(base, 360), -3)),
    durationMinutes: 60,
    status: 'CANCELLED',
    attendanceStatus: 'CANCELLED',
    location: 'Sala de alongamentos',
    planId: 'tp-004',
    planTitle: 'Programa mobilidade avançada',
    focusArea: 'Mobilidade',
    intensity: 'Baixa',
    notes: 'Cliente cancelou por motivos pessoais.',
  },
  {
    trainerSeed: 'trainer-joao',
    id: 'tw-006',
    title: 'Treino outdoor equipa',
    trainerId: 'trainer-joao',
    clientId: 'client-equipa',
    clientName: 'Equipa Lince',
    clientEmail: 'equipa.lince@fitnesspro.pt',
    startAt: iso(addDays(addMinutes(base, 540), 3)),
    endAt: iso(addDays(addMinutes(base, 660), 3)),
    durationMinutes: 120,
    status: 'SCHEDULED',
    attendanceStatus: 'CONFIRMED',
    location: 'Parque da cidade',
    planId: 'tp-009',
    planTitle: 'Condicionamento funcional corporativo',
    focusArea: 'Condicionamento',
    intensity: 'Alta',
    notes: 'Verificar disponibilidade de material externo.',
  },
  {
    trainerSeed: 'trainer-sofia',
    id: 'tw-101',
    title: 'Avaliação inicial',
    trainerId: 'trainer-sofia',
    clientId: 'client-maria',
    clientName: 'Maria Costa',
    clientEmail: 'maria.costa@fitnesspro.pt',
    startAt: iso(addMinutes(base, 120)),
    endAt: iso(addMinutes(base, 165)),
    durationMinutes: 45,
    status: 'COMPLETED',
    attendanceStatus: 'COMPLETED',
    location: 'Gabinete avaliação',
    planId: 'tp-006',
    planTitle: 'Reforço de core e estabilidade',
    focusArea: 'Avaliação',
    intensity: 'Baixa',
    notes: 'Enviar relatório de avaliação.',
  },
  {
    trainerSeed: 'trainer-sofia',
    id: 'tw-102',
    title: 'HIIT focado em core',
    trainerId: 'trainer-sofia',
    clientId: 'client-luis',
    clientName: 'Luís Carvalho',
    clientEmail: 'luis.carvalho@fitnesspro.pt',
    startAt: iso(addDays(addMinutes(base, 240), 2)),
    endAt: iso(addDays(addMinutes(base, 300), 2)),
    durationMinutes: 60,
    status: 'SCHEDULED',
    attendanceStatus: 'PENDING',
    location: 'Estúdio 1',
    planId: 'tp-007',
    planTitle: 'Plano manutenção verão',
    focusArea: 'Resistência',
    intensity: 'Alta',
    notes: 'Adicionar circuito com kettlebell.',
  },
  {
    trainerSeed: 'trainer-sofia',
    id: 'tw-103',
    title: 'Sessão recuperação pós corrida',
    trainerId: 'trainer-sofia',
    clientId: 'client-joana',
    clientName: 'Joana Faria',
    clientEmail: 'joana.faria@fitnesspro.pt',
    startAt: iso(addDays(addMinutes(base, 360), -2)),
    endAt: iso(addDays(addMinutes(base, 420), -2)),
    durationMinutes: 60,
    status: 'COMPLETED',
    attendanceStatus: 'COMPLETED',
    location: 'Sala de alongamentos',
    planId: 'tp-008',
    planTitle: 'Resistência aeróbica intermédia',
    focusArea: 'Mobilidade',
    intensity: 'Baixa',
    notes: 'Recuperação adequada, planear nova avaliação.',
  },
  {
    trainerSeed: 'trainer-sofia',
    id: 'tw-104',
    title: 'Treino força total',
    trainerId: 'trainer-sofia',
    clientId: 'client-beatriz',
    clientName: 'Beatriz Lemos',
    clientEmail: 'beatriz.lemos@fitnesspro.pt',
    startAt: iso(addDays(addMinutes(base, 480), 5)),
    endAt: iso(addDays(addMinutes(base, 540), 5)),
    durationMinutes: 60,
    status: 'SCHEDULED',
    attendanceStatus: 'UPCOMING',
    location: 'Box principal',
    planId: 'tp-011',
    planTitle: 'Plano força atletas',
    focusArea: 'Força',
    intensity: 'Alta',
    notes: 'Preparar progressão de peso.',
  },
  {
    trainerSeed: 'trainer-tomas',
    id: 'tw-201',
    title: 'Treino funcional empresarial',
    trainerId: 'trainer-tomas',
    clientId: 'client-corp',
    clientName: 'Empresa Atlas',
    clientEmail: 'atlas@fitnesspro.pt',
    startAt: iso(addMinutes(base, 180)),
    endAt: iso(addMinutes(base, 300)),
    durationMinutes: 120,
    status: 'SCHEDULED',
    attendanceStatus: 'CONFIRMED',
    location: 'Sala multiusos',
    planId: 'tp-020',
    planTitle: 'Plano corporativo Atlas',
    focusArea: 'Condicionamento',
    intensity: 'Média',
    notes: 'Confirmar logística com RH.',
  },
  {
    trainerSeed: 'trainer-tomas',
    id: 'tw-202',
    title: 'Sessão de reavaliação',
    trainerId: 'trainer-tomas',
    clientId: 'client-tiago',
    clientName: 'Tiago Neves',
    clientEmail: 'tiago.neves@fitnesspro.pt',
    startAt: iso(addDays(addMinutes(base, 60), -5)),
    endAt: iso(addDays(addMinutes(base, 120), -5)),
    durationMinutes: 60,
    status: 'COMPLETED',
    attendanceStatus: 'NO_SHOW',
    location: 'Gabinete avaliação',
    planId: 'tp-010',
    planTitle: 'Plano detox pós-época',
    focusArea: 'Avaliação',
    intensity: 'Baixa',
    notes: 'Cliente faltou, reagendar para próxima semana.',
  },
  {
    trainerSeed: 'trainer-tomas',
    id: 'tw-203',
    title: 'Sessão de mobilidade empresarial',
    trainerId: 'trainer-tomas',
    clientId: 'client-corp-2',
    clientName: 'Equipa Horizonte',
    clientEmail: 'equipa.horizonte@fitnesspro.pt',
    startAt: iso(addDays(addMinutes(base, 420), 4)),
    endAt: iso(addDays(addMinutes(base, 480), 4)),
    durationMinutes: 60,
    status: 'SCHEDULED',
    attendanceStatus: 'PENDING',
    location: 'Sala multiusos',
    planId: 'tp-021',
    planTitle: 'Plano mobilidade equipa',
    focusArea: 'Mobilidade',
    intensity: 'Baixa',
    notes: 'Confirmar lista de participantes.',
  },
];

export function getTrainerWorkoutsFallback(trainerId: string): TrainerWorkoutsDashboardData {
  const sample = FALLBACK_TRAINER_WORKOUTS.filter((row) => row.trainerSeed === trainerId);
  const dataset = (sample.length ? sample : FALLBACK_TRAINER_WORKOUTS.filter((row) => row.trainerSeed === 'trainer-joao')).map(
    ({ trainerSeed: _trainerSeed, ...rest }) => rest,
  );
  return buildTrainerWorkoutsDashboard(dataset, { supabase: false });
}

export function getTrainerWorkoutRecordsFallback(trainerId: string): TrainerWorkoutRecord[] {
  const sample = FALLBACK_TRAINER_WORKOUTS.filter((row) => row.trainerSeed === trainerId);
  return (sample.length ? sample : FALLBACK_TRAINER_WORKOUTS.filter((row) => row.trainerSeed === 'trainer-joao')).map(
    ({ trainerSeed: _trainerSeed, ...rest }) => rest,
  );
}
