#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🧪 Type checking..."
node scripts/precommit.cjs
status=$?

if [ $status -ne 0 ]; then
  echo "❌ Pre-commit falhou"
  exit $status
fi

echo "✅ Pre-commit OK"
